apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "msa-mobile-web-ui.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |-
    console.log('Config loaded');

  nginx.conf: |-
    worker_processes auto;
    pid        /tmp/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /tmp/access.log  main;
        error_log   /tmp/error.log debug;
        sendfile        on;

        keepalive_timeout  65;

        client_body_temp_path /tmp/nginx-client-body;
        proxy_temp_path       /tmp/nginx-proxy;
        fastcgi_temp_path     /tmp/nginx-fastcgi;
        uwsgi_temp_path       /tmp/nginx-uwsgi;
        scgi_temp_path        /tmp/nginx-scgi;

        server {
            listen       8080;
            server_name  _;
            error_log   /tmp/error.log debug;

            #charset koi8-r;
            #access_log  /var/log/nginx/host.access.log  main;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                try_files $uri /index.html;
            }
    
            location /api/v1 {
                proxy_pass http://mobile-backend-resource-manager.apps.msa31.do.neoflex.ru:80;
            }
        }
    }