const actionTypes = {
  CHANGE_ACTIVE_TAB: "CONFIG/CHANGE_ACTIVE_TAB",
  CHANGE_PREVIEW_MODE: "CONFIG/CHANGE_PREVIEW_MODE",
  SET_SELECTED_BLOCK: "LAYOUT/SET_SELECTED_BLOCK",
  PUSH_BLOCK: "LAYOUT/PUSH_BLOCK",
  PUSH_BLOCK_INSIDE: "LAYOUT/PUSH_BLOCK_INSIDE",
  CHANGE_BLOCK_DATA: "LAYOUT/CHANGE_BLOCK_DATA",
  REPLACE_ELEMENT: "LAYOUT/REPLACE_ELEMENT",
  REORDER_LAYOUT: "LAYOUT/REORDER_LAYOUT",
  DELETE_BLOCK: "LAYOUT/DELETE_BLOCK",
  CHANGE_DOCUMENT_ID: "LAYOUT/CHANGE_DOCUMENT_ID",
  EDIT_SCREEN_NAME: "OUTPUT/EDIT_SCREEN_NAME",
};

export const ItemTypes = {
  BOX: "box",
};

export default actionTypes;
